// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/vision/v1p4beta1/image_annotator.proto

package com.google.cloud.vision.v1p4beta1;

public interface TextDetectionParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.cloud.vision.v1p4beta1.TextDetectionParams)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * By default, Cloud Vision API only includes confidence score for
   * DOCUMENT_TEXT_DETECTION result. Set the flag to true to include confidence
   * score for TEXT_DETECTION as well.
   * </pre>
   *
   * <code>bool enable_text_detection_confidence_score = 9;</code>
   * @return The enableTextDetectionConfidenceScore.
   */
  boolean getEnableTextDetectionConfidenceScore();
}
